annotations:
  category: apps
  artifacthub.io/category: networking
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: iPerf3 is a tool for active measurements of the maximum achievable bandwidth on IP networks. It supports tuning of various parameters related to timing, buffers and protocols (TCP, UDP, SCTP with IPv4 and IPv6). For each test it reports the bandwidth, loss, and other parameters.
engine: gotpl
home: https://iperf.fr/
icon: https://iperf.fr/images/logo_iperf_command.png
keywords:
  - network
  - apps
  - gradiant
  - k8s
maintainers:
  - email: admin@gradiant.org
    name: Gradiant
name: iperf3
sources:
  - https://iperf.fr/
version: 0.1.3
