apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: values-custom-open5gs
    files:
      - values.yaml=../charts/respons/values-custom-open5gs.yaml
  # - name: values-custom-ueransim-gnb
  #   files:
  #     - values.yaml=../charts/respons/values-custom-ueransim-gnb.yaml
configurations:
  - kustomizeconfig.yaml
