apiVersion: v2
appVersion: "2.7.2"
description: >
  Helm chart to deploy Open5gs WebUI service on Kubernetes.
home: https://github.com/gradiant/5g-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs-logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
- email: avrodriguez@gradiant.org
  name: avrodriguez
name: open5gs-webui
version: 2.2.5
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - ngc
  - gradiant
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: mongodb
    version: ~12.1.19
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
