apiVersion: v2
appVersion: stable-6865
description: >
  Helm chart to deploy Jitsi on Kubernetes.
home: https://github.com/gradiant/openverso-charts
sources:
  - https://github.com/jitsi-contrib/jitsi-helm
maintainers:
  - email: mmarquez@gradiant.org
    name: mmarquez999
  - email: cgiraldo@gradiant.org
    name: cgiraldo
icon: https://jitsi.org/wp-content/uploads/2018/11/jitsi-logo-blue-grey-text.png
name: jitsi
version: 0.0.3
keywords:
  - network
  - apps
  - k8s
dependencies:
  - name: prosody
    condition: prosody.enabled
    version: 1.2.2
