apiVersion: v2
appVersion: "2.7.0"
description: >
  Helm chart to deploy Open5gs BSF service on Kubernetes.
home: https://github.com/gradiant/openverso-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs-logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: open5gs-bsf
version: 2.2.0
keywords:
  - ngc
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
