apiVersion: v1
appVersion: "23.11"
description: >
  srsRAN4g enodeb + ue.
home: https://github.com/Gradiant/charts
sources:
  - https://github.com/srsran/srsRAN_4G
icon: https://docs.srsran.com/en/latest/_static/logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: srsran-4g-enb-zmq
version: 0.2.0
keywords:
  - lte
  - enodeb
