{{- if .Values.ingress.enabled -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
{{- if and .Values.ingress.ingressClassName (semverCompare ">=1.19-0" $kubeVersion) }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | default (printf "%s-%s.ingress.lab5g.gradiant.org" .Release.Name .Release.Namespace) }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend: 
              service:
                name: {{ include "common.names.fullname" $ }}
                port: 
                  name: http
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | default (printf "%s-%s.ingress.lab5g.gradiant.org" .Release.Name .Release.Namespace) }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
  {{- end }}
{{- end }}
