apiVersion: v2
appVersion: "2.4.9"
description: >
  Helm chart to deploy Open5gs UDM service on Kubernetes.
home: https://github.com/gradiant/openverso-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs_logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: open5gs-udm
version: 2.0.0
keywords:
  - ngc
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: open5gs-nrf
    version: 2.0.0
    repository: "file://../open5gs-nrf"
    condition: open5gs-nrf.enabled