apiVersion: v2
appVersion: "2.7.2"
description: >
  Helm chart to deploy Open5gs NSSF service on Kubernetes.
home: https://github.com/gradiant/5g-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs-logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: open5gs-nssf
version: 2.2.5
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - ngc
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
