amf:
  hostname: open5gs-amf-ngap

gnb:
  hostname: ueransim-gnb

mcc: '999'
mnc: '70'
key: 465B5CE8B199B49FAA5F0A2EE238A6BC
op: E8ED289DEBA952E4283B54E88E6183CA
opType: OPC
gnb:
  hostname: ueransim-gnb
sst: 1
sd: "0x111111"
apnList:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: "0x111111"
    emergency: false

ues:
  enabled: true
  count: 449
  initialMSISDN: '0000000001'
