apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-amf
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: amf
spec:
  ports:
  - name: sbi
    port: 7777
    protocol: TCP
  - name: ngap 
    port: 38412
    protocol: SCTP

  publishNotReadyAddresses: true
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: amf
