apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-amf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: amf
spec:
  replicas: 1
  serviceName: {{ include "open5gs.fullname" . }}-amf
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: amf
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: amf
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{ include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: amf
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-amfd"]
        ports:
        - name: sbi
          containerPort: 7777
          protocol: TCP
        - name: ngap 
          containerPort: 38412
          protocol: UDP
        # livenessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: sbi
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
{{ toYaml .Values.amf.resources | indent 10 }}
        volumeMounts:
        - name: amf-config
          mountPath:  /opt/open5gs/etc/open5gs/amf.yaml
          subPath: "amf.yaml"
      volumes:
      - name: amf-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-amf
