{{- if .Values.ausf.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-ausf
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: ausf
spec:
  ports:
  - name: sbi
    port: 7777
    protocol: TCP

  publishNotReadyAddresses: true
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: ausf
{{- end }}