{{- if .Values.mme.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}-mme
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: mme
spec:
  replicas: 1
  serviceName: {{ include "common.names.fullname" . }}-mme
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: mme
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: mme
    spec:
{{- include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: mme
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-mmed"]
        ports:
        - name: s6a
          containerPort: 3868
          protocol: SCTP
        livenessProbe:
          tcpSocket:
            port: s6a
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: s6a
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
{{ toYaml .Values.mme.resources | indent 10 }}
        volumeMounts:
        - name: mme-config
          mountPath: /opt/open5gs/etc/open5gs/mme.yaml
          subPath: "mme.yaml"
        - name: mme-diameter-config
          mountPath: /opt/open5gs/etc/freeDiameter/mme.conf
          subPath: "diameter-mme.conf"
      volumes:
      - name: mme-config
        configMap:
          name: {{ include "common.names.fullname" . }}-mme
      - name: mme-diameter-config
        configMap:
          name: {{ include "common.names.fullname" . }}-mme-diameter
{{- end }}