apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-sgwu
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: sgwu
spec:
  ports:
   - name: gtp-u
     port: 2152
     protocol: UDP
   - name: pfcp
     port: 8805
     protocol: UDP  
  publishNotReadyAddresses: true
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: sgwu
