apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-smf
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: smf
spec:
  replicas: 1
  serviceName: {{ include "open5gs.name" . }}-smf
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: smf
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: smf
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{- include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: smf
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-smfd"]
        ports:
        - name: gtp-u
          containerPort: 2152
          protocol: UDP
        - name: gtp-c
          containerPort: 2123
          protocol: UDP
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        - name: s6a
          containerPort: 3868
          protocol: SCTP
        - name: sbi
          containerPort: 7777
          protocol: TCP
        # livenessProbe:
        #   tcpSocket:
        #     port: gx
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   tcpSocket:
        #     port: gx
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
{{ toYaml .Values.smf.resources | indent 10 }}
        volumeMounts:
        - name: smf-config
          mountPath:  /opt/open5gs/etc/open5gs/smf.yaml
          subPath: "smf.yaml"
        - name: smf-diameter-config
          mountPath:  /opt/open5gs/etc/freeDiameter/smf.conf
          subPath: "diameter-smf.conf"
      volumes:
      - name: smf-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-smf
      - name: smf-diameter-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-smf-diameter
