apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "open5gs.fullname" . }}-udm
  labels:
{{ include "open5gs.labels.standard" . | indent 4 }}
    app.kubernetes.io/component: udm
spec:
  replicas: 1
  serviceName: {{ include "open5gs.fullname" . }}-udm
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "open5gs.name" . }}
      app.kubernetes.io/component: udm
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
     labels:
        app.kubernetes.io/name: {{ include "open5gs.name" . }}
        app.kubernetes.io/component: udm
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
{{ include "open5gs.imagePullSecrets" . | indent 6 }}
      containers:
      - name: udm
        image: {{ template "open5gs.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["open5gs-udmd"]
        ports:
        - name: sbi
          containerPort: 7777
          protocol: TCP
        # livenessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # readinessProbe:
        #   tcpSocket:
        #     port: s6a
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        resources:
{{ toYaml .Values.udm.resources | indent 10 }}
        volumeMounts:
        - name: udm-config
          mountPath:  /opt/open5gs/etc/open5gs/udm.yaml
          subPath: "udm.yaml"
      volumes:
      - name: udm-config
        configMap:
          name: {{ include "open5gs.fullname" . }}-udm
