apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open5gs
  namespace: openverso
spec:
  interval: 30s
  releaseName: open5gs
  chart:
    spec:
      chart: ./charts/open5gs
      sourceRef:
        kind: GitRepository
        name: openverso
        namespace: openverso
  valuesFrom:
    - kind: ConfigMap
      name: values-custom-open5gs
  targetNamespace: openverso
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: ueransim-gnb
#   namespace: openverso
# spec:
#   interval: 30s
#   releaseName: ueransim-gnb
#   chart:
#     spec:
#       chart: ./charts/ueransim-gnb
#       sourceRef:
#         kind: GitRepository
#         name: openverso
#         namespace: openverso
#   valuesFrom:
#     - kind: ConfigMap
#       name: values-custom-ueransim-gnb
#   targetNamespace: openverso
