image:
  registry: docker.io
  repository: openverso/srsran
  tag: "22_04_1"
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #  - regcred

ue:
  opc: 'E8ED289DEBA952E4283B54E88E6183CA'
  k: '465B5CE8B199B49FAA5F0A2EE238A6BC'
  imsi: '999700000000001'
  imei: '353490069873319'
  resources: {}

enb:
  mme: mme
  mcc: '999'
  mnc: '70'
  tac: '0001'
  resources: {}
