apiVersion: v2
appVersion: "2.4.8"
description: >
  Helm chart to deploy Open5gs services on Kubernetes.
home: https://github.com/gradiant/openverso-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs_logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: open5gs
version: 1.2.2
keywords:
  - epc
  - ngc
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: mongodb
    version: ~12.1.19
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
