apiVersion: v1
appVersion: "23.11"
description: >
  SRS ue
home: https://github.com/Gradiant/charts
sources:
  - https://github.com/srsran/srsRAN_4G
icon: https://docs.srsran.com/en/latest/_static/logo.png
maintainers:
- email: cgiraldo@gradiant.org
  name: cgiraldo
name: srs-ue
version: 0.2.0
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - lte
  - ue
