logger:
{{ toYaml .Values.amf.logger | indent 2 }}

{{- if .Values.amf.parameter }}
parameter:
{{ toYaml .Values.amf.parameter | indent 2 }}
{{- end }}

{{- if .Values.amf.max }}
max:
{{ toYaml .Values.amf.max | indent 2 }}
{{- end }}

{{- if .Values.amf.pool }}
pool:
{{ toYaml .Values.amf.pool | indent 2 }}
{{- end }}


amf:
  sbi:
    dev: eth0
    port: 7777
  ngap:
    dev: eth0
  guami:
    plmn_id:
      mcc: {{ .Values.amf.mcc }}
      mnc: {{ .Values.amf.mnc }}
    amf_id: 
      region: {{ .Values.amf.region }}
      set: {{ .Values.amf.set }}
  tai:
    plmn_id:
      mcc: {{ .Values.amf.mcc }}
      mnc: {{ .Values.amf.mnc }}
    tac: {{ .Values.amf.tac }}
  plmn_support:
    plmn_id:
      mcc: {{ .Values.amf.mcc }}
      mnc: {{ .Values.amf.mnc }}
    s_nssai: 
      sst: {{ .Values.amf.sst }}
  security:
      integrity_order : [ NIA2, NIA1, NIA0 ]
      ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
      full: Open5GS
  amf_name: open5gs-amf0

nrf:
  sbi:
    - name: "{{ include "open5gs.fullname" . }}-nrf"
      port: 7777
