logger:
{{ toYaml .Values.mme.logger | indent 2 }}

{{- if .Values.mme.parameter }}
parameter:
{{ toYaml .Values.mme.parameter | indent 2 }}
{{- end }}

{{- if .Values.mme.max }}
max:
{{ toYaml .Values.mme.max | indent 2 }}
{{- end }}

{{- if .Values.mme.pool }}
pool:
{{ toYaml .Values.mme.pool | indent 2 }}
{{- end }}


mme:
  freeDiameter: mme.conf
  s1ap:
    dev: eth0
  gtpc:
    dev: eth0
  gummei:
{{ toYaml .Values.mme.gummei | indent 4 }}
  tai:
{{ toYaml .Values.mme.tai | indent 4 }}
  security:
      integrity_order : [ EIA1, EIA2, EIA0 ]
      ciphering_order : [ EEA0, EEA1, EEA2 ]
  network_name:
      full: Gradiant4G

sgwc:
  gtpc:
    - name: "{{ include "common.names.fullname" . }}-sgwc"

smf:
  gtpc:
    - name: "{{ include "common.names.fullname" . }}-smf"
